name: PostgreSQL service example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        container: node:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_DB: postgres_db
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Ping Postgres
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
        env:
          # postgress password is required; alternatively, you can run:
          # `PGPASSWORD=postgres_password psql ...`
          PGPASSWORD: postgres_password
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
